In [1]:
!nvidia-smi


Sun Nov  5 23:54:56 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.92                 Driver Version: 545.92       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0               7W /  35W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.198  Python-3.11.5 torch-2.1.0+cpu CPU (AMD Ryzen 7 5800HS with Radeon Graphics)
Setup complete  (16 CPUs, 15.4 GB RAM, 441.2/475.3 GB disk)


In [3]:
from ultralytics import YOLO

from IPython.display import display, Image

In [5]:
ls


 Volume in drive C is OS
 Volume Serial Number is 7453-779E

 Directory of c:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model

03-11-2023  18:31    <DIR>          .
04-11-2023  22:00    <DIR>          ..
16-10-2023  18:56         7,056,616 cars.mp4
03-11-2023  18:32    <DIR>          data
16-10-2023  18:56               435 data.yaml
16-10-2023  18:56             6,556 README.md
16-10-2023  18:56    <DIR>          runs
16-10-2023  18:56            49,063 yolo.ipynb
16-10-2023  18:56        22,573,363 yolov8s.pt
               5 File(s)     29,686,033 bytes
               4 Dir(s)  36,592,553,984 bytes free


In [10]:
import subprocess

# Run the YOLO task using subprocess from the current directory
yolo_command = "yolo task=detect mode=train model=yolov8s.pt data=data.yaml epochs=1 imgsz=640 plots=True"
subprocess.run(yolo_command, shell=True)

CompletedProcess(args='yolo task=detect mode=train model=yolov8s.pt data=data.yaml epochs=1 imgsz=640 plots=True', returncode=1)

In [13]:
!yolo task=detect mode=val model=runs/detect/train/weights/best.pt data=data.yaml

Ultralytics YOLOv8.0.198  Python-3.11.5 torch-2.1.0+cpu CPU (AMD Ryzen 7 5800HS with Radeon Graphics)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs

  0%|          | 0.00/755k [00:00<?, ?B/s]
  5%|▌         | 40.0k/755k [00:00<00:01, 404kB/s]
 16%|█▌        | 120k/755k [00:00<00:01, 620kB/s] 
 31%|███       | 232k/755k [00:00<00:00, 779kB/s]
 42%|████▏     | 320k/755k [00:00<00:00, 814kB/s]
 59%|█████▉    | 448k/755k [00:00<00:00, 956kB/s]
 81%|████████  | 608k/755k [00:00<00:00, 1.07MB/s]
100%|██████████| 755k/755k [00:00<00:00, 1.04MB/s]

val: Scanning C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\valid\labels...:   0%|          | 0/154 [00:00<?, ?it/s]
val: Scanning C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\valid\labels... 87 images, 14 backgrounds, 0 corrupt:  56%|█████▋    | 87/154 [00:00<00:00, 848.82it/s]
val: Scanning C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\valid\label

In [14]:
!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt conf=0.25 source=data/test/images

Ultralytics YOLOv8.0.198  Python-3.11.5 torch-2.1.0+cpu CPU (AMD Ryzen 7 5800HS with Radeon Graphics)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs

image 1/157 c:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\test\images\5_17_jpg.rf.0611b10e50517e4323c47fc36301167c.jpg: 640x640 (no detections), 173.8ms
image 2/157 c:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\test\images\5_22_jpg.rf.368e2a41bf84be83076f603939cbd052.jpg: 640x640 (no detections), 168.3ms
image 3/157 c:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\test\images\5_28_jpg.rf.3eabd78da3af251b71e0089ac63f9c88.jpg: 640x640 (no detections), 145.9ms
image 4/157 c:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\test\images\ezgif-frame-007_jpg.rf.ceac019216ee1df6dffdd54ec8e49012.jpg: 640x640 (no detections), 130.6ms
image 5/157 c:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\data\test\images\ezgif-frame-0

In [35]:
!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt source="C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4"

Ultralytics YOLOv8.0.198  Python-3.11.5 torch-2.1.0+cpu CPU (AMD Ryzen 7 5800HS with Radeon Graphics)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs

video 1/1 (1/529) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 352x640 (no detections), 114.0ms
video 1/1 (2/529) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 352x640 (no detections), 104.6ms
video 1/1 (3/529) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 352x640 (no detections), 103.8ms
video 1/1 (4/529) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 352x640 (no detections), 96.3ms
video 1/1 (5/529) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 352x640 (no detections), 89.4ms
video 1/1 (6/529) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 352x640 (no detections), 85.4ms
video 1/1 (7/529) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\

In [34]:
!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt source="C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4" conf=0.01 | findstr /C:"ACCIDENT" && echo "Accident is present" || echo "No accident detected"


"No accident detected"


Ultralytics YOLOv8.0.198  Python-3.11.5 torch-2.1.0+cpu CPU (AMD Ryzen 7 5800HS with Radeon Graphics)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs

video 1/1 (1/356) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 384x640 (no detections), 140.5ms
video 1/1 (2/356) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 384x640 (no detections), 120.5ms
video 1/1 (3/356) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 384x640 1 Accident, 116.9ms
video 1/1 (4/356) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 384x640 1 Accident, 115.4ms
video 1/1 (5/356) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 384x640 1 Accident, 124.0ms
video 1/1 (6/356) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 384x640 1 Accident, 99.7ms
video 1/1 (7/356) C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\car.mp4: 384x640 1

In [32]:
import cv2
import torch
import numpy as np

def detect_objects(image, model_path, conf_thres=0.4):
    print(f"Model path: {model_path}")  # Add this line for debugging
    # Load the model
    net = cv2.dnn.readNet(model_path)

    # Get the names of the output layers
    layer_names = net.getLayerNames()
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]

    # Resize the image and normalize pixel values to [0, 1]
    blob = cv2.dnn.blobFromImage(image, 1/255, (416, 416), swapRB=True, crop=False)

    # Set the input of the network
    net.setInput(blob)

    # Forward pass through the network
    outputs = net.forward(output_layers)

    # Parse the outputs and get the class IDs, confidences, and bounding boxes
    class_ids, confidences, boxes = [], [], []
    for output in outputs:
        for detection in output:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]
            if confidence > conf_thres:
                center_x, center_y, width, height = detection[:4] * np.array(image.shape[1], image.shape[0], image.shape[1], image.shape[0])
                x, y = int(center_x - width/2), int(center_y - height/2)
                w, h = int(width), int(height)
                class_ids.append(class_id)
                confidences.append(float(confidence))
                boxes.append([x, y, w, h])

    # Return the class IDs, confidences, and bounding boxes
    return class_ids, confidences, boxes

# Load the output image
output_image = cv2.imread(r"C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\runs\detect\predict2\testing1.jpg")

# Set the path to your YOLO model
model_path = r"C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\runs\detect\train\weights\best.pt"
print(f"Output image path: {output_image}")

# Get the number of objects detected
num_objects = len(detect_objects(output_image, model_path))
print(f"Number of objects detected: {num_objects}")

# Set a threshold for the number of objects
if num_objects > 0:
    message = "Accident detected!"
else:
    message = "No accidents detected."

print(message)


Output image path: [[[ 37  68  53]
  [ 19  42  34]
  [ 34  34  46]
  ...
  [ 98  97 123]
  [ 91  90 116]
  [ 39  38  64]]

 [[  3  30  14]
  [  6  26  14]
  [ 28  29  33]
  ...
  [ 98  97 123]
  [ 78  77 103]
  [ 41  40  66]]

 [[  0  13   0]
  [  2  16   0]
  [ 22  19  11]
  ...
  [108 107 133]
  [ 70  69  95]
  [ 45  44  70]]

 ...

 [[ 78  73  74]
  [ 79  74  75]
  [ 45  43  43]
  ...
  [142 125 116]
  [142 125 116]
  [142 125 116]]

 [[ 70  65  66]
  [ 83  78  79]
  [ 57  55  55]
  ...
  [143 124 116]
  [143 124 116]
  [143 124 116]]

 [[ 64  59  60]
  [ 86  81  82]
  [ 74  72  72]
  ...
  [143 124 116]
  [143 124 116]
  [143 124 116]]]
Model path: C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\runs\detect\train\weights\best.pt


error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn_read.cpp:56: error: (-2:Unspecified error) Cannot determine an origin framework of files: C:\Users\Ankit Singh\Desktop\Projects\Accident-Detection-Model\runs\detect\train\weights\best.pt in function 'cv::dnn::dnn4_v20230620::readNet'


In [ ]:
import cv2

# Load the pre-trained human body classifier
body_cascade = cv2.CascadeClassifier('haarcascade_fullbody.xml')

# Initialize the video capture
cap = cv2.VideoCapture(0)  # You can change the argument to specify a video file

while True:
    # Read a frame from the video capture
    ret, frame = cap.read()

    # Convert the frame to grayscale for better performance
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Detect human bodies in the frame
    bodies = body_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    # Draw rectangles around the detected bodies
    for (x, y, w, h) in bodies:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # Display the frame with detected bodies
    cv2.imshow('Human Detection', frame)

    # Break the loop when 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture and close all OpenCV windows
cap.release()
cv2.destroyAllWindows()


In [1]:
import cv2

# Load the pre-trained Haar Cascade classifiers for both humans and cars
human_cascade = cv2.CascadeClassifier('haarcascade_fullbody.xml')
car_cascade = cv2.CascadeClassifier('haarcascade_car.xml')

# Initialize the laptop camera
cap = cv2.VideoCapture(0)

while True:
    # Read a frame from the camera
    ret, frame = cap.read()

    # Convert the frame to grayscale for better performance
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Detect humans in the frame
    humans = human_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    # Detect cars in the frame
    cars = car_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    # Draw rectangles around the detected humans
    for (x, y, w, h) in humans:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

    # Draw rectangles around the detected cars
    for (x, y, w, h) in cars:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 2)

    # Display the frame with detected objects
    cv2.imshow('Object Detection', frame)

    # Break the loop when 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the camera and close all OpenCV windows
cap.release()
cv2.destroyAllWindows()
